name:                hlibcpuid
version:             0.2.0
github:              "dtaskoff/hlibcpuid"
license:             MIT
author:              "Daniel Taskoff"
maintainer:          "daniel.taskoff@gmail.com"
copyright:           "2020 (c) Daniel Taskoff"

synopsis:            Bindings to https://github.com/anrieff/libcpuid
category:            Foreign, System

description:         Please see the README on GitHub at <https://github.com/dtaskoff/hlibcpuid#readme>

extra-source-files:
- README.md
- CHANGELOG.md

data-files:
- libcpuid/COPYING

dependencies:
- base >= 4.7 && < 5

default-extensions:
- BlockArguments
- LambdaCase
- RecordWildCards
- TypeApplications

library:
  source-dirs: src
  include-dirs: libcpuid/libcpuid

  install-includes:
  - libcpuid/libcpuid/amd_code_t.h
  - libcpuid/libcpuid/asm-bits.h
  - libcpuid/libcpuid/intel_code_t.h
  - libcpuid/libcpuid/libcpuid.h
  - libcpuid/libcpuid/libcpuid_constants.h
  - libcpuid/libcpuid/libcpuid_internal.h
  - libcpuid/libcpuid/libcpuid_types.h
  - libcpuid/libcpuid/libcpuid_util.h
  - libcpuid/libcpuid/rdtsc.h
  - libcpuid/libcpuid/recog_amd.h
  - libcpuid/libcpuid/recog_intel.h

  c-sources:
  - libcpuid/libcpuid/asm-bits.c
  - libcpuid/libcpuid/cpuid_main.c
  - libcpuid/libcpuid/libcpuid_util.c
  - libcpuid/libcpuid/msrdriver.c
  - libcpuid/libcpuid/rdmsr.c
  - libcpuid/libcpuid/rdtsc.c
  - libcpuid/libcpuid/recog_amd.c
  - libcpuid/libcpuid/recog_intel.c

  cc-options: -DVERSION="0.4.1"

ghc-options:
- -Wall
- -fwarn-incomplete-uni-patterns
- -fwarn-incomplete-record-updates

executables:
  cpuid:
    main: Main.hs
    source-dirs: app

    dependencies: hlibcpuid
