name:                hlibcpuid
version:             0.1.0.0
github:              "dtaskoff/hlibcpuid"
license:             MIT
author:              "Daniel Taskoff"
maintainer:          "daniel.taskoff@gmail.com"
copyright:           "2020 Daniel Taskoff"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Bindings to https://github.com/anrieff/libcpuid
category:            Foreign, System

description:         Please see the README on GitHub at <https://github.com/dtaskoff/hlibcpuid#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  include-dirs: libcpuid/libcpuid
  c-sources:
  - libcpuid/libcpuid/asm-bits.c
  - libcpuid/libcpuid/cpuid_main.c
  - libcpuid/libcpuid/libcpuid_util.c
  - libcpuid/libcpuid/msrdriver.c
  - libcpuid/libcpuid/rdmsr.c
  - libcpuid/libcpuid/rdtsc.c
  - libcpuid/libcpuid/recog_amd.c
  - libcpuid/libcpuid/recog_intel.c
  cc-options: -DVERSION="0.4.1"
